
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.227.205:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: fzh020688

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.example.blog: info
  file: log/blog-pro.log
server:
  port: 8080
